### ISSUE TITLE
Trouble figuring out some functions of PYTEARCAT

### ISSUE THREAD

**Issue by GravitoMagnetism** [pytearcat/pytearcat#10]
First off, I'd like to say that this code is awesome and has been doing a better (faster) job of calculating GR tensors than Einsteinpy! However, there are a few things not mentioned in the PDF that I'd like to ask about.
-The PDF says you can overwrite functions (which I interpreted to mean replacing f(x) with the actual function). However, it doesn't say *how* to do that. I tried using f='x**2', for example, but it doesn't work. So how does one go about overwriting functions?
-I'd like to plot components of the tensors calculated by your program with respect to some coordinates (For example, plotting the 1,1 component of a calculated Einstein tensor with respect to x and t), but I can't seem to find any way to do this. Is it possible to do this in PYTEARCAT?
Thank you for any help, and I apologize if this is the wrong place to ask these questions.

**Comment by jmsureda** [comment]
Hi GravitoMagnetism! 

Thank you for your interest in Pytearcat. 

The quick answer to your question is no, pytearcat cannot replace functions that way. What is referred to in the paper is that you can overwrite, for instance, a function f(x) with f(t) so that you get the correct dependence with the argument of the function when performing the calculations. 

What you were expecting is, for now, beyond the scope of pytearcat as it is intended to work with more arbitrary functions for now. If you need to replace functions, you should use `lambdify` from `sympy` as every element of a tensor object is a `sympy` expression so you can treat it that way. 

And don't apologize, this is the right place to ask these questions! :)

**Comment by jmsureda** [comment]
Closing this as it is not an issue.
